version: 2

jobs:
  install:

    docker:
      - image: circleci/node:10

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-npm-deps-{{ checksum "package-lock.json" }}
          - v1-npm-deps-

      - run: npm --production=false install

      - save_cache:
          paths:
            - node_modules
          key: v1-npm-deps-{{ checksum "package-lock.json" }}

      - persist_to_workspace:
          root: ~/
          paths:
            - repo
            - .ssh

  lint:

    docker:
      - image: circleci/node:10

    working_directory: ~/repo

    steps:
      - attach_workspace:
          at: ~/

      - run:
          name: Linting
          command: npm run lint

  build:

    docker:
      - image: circleci/node:10

    working_directory: ~/repo

    steps:
      - attach_workspace:
          at: ~/

      - run:
          name: Build
          command: npm run build

  deploy:

    docker:
      - image: circleci/node:10
    environment:
      GIT_AUTHOR_EMAIL: circleci@example.com
      GIT_AUTHOR_NAME: Circle CI
      GIT_COMMITTER_EMAIL: circleci@example.com
      GIT_COMMITTER_NAME: Circle CI

    working_directory: ~/repo

    steps:
      - attach_workspace:
          at: ~/

      - run:
          name: Deploy
          command: npm run deploy

workflows:
  version: 2
  main:
    jobs:
      - install
      - lint:
          requires:
            - install
      - build:
          requires:
            - install
      - deploy:
          requires:
            - lint
            - build
          filters:
            branches:
              only:
                - master
